source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.3", ">= 7.0.3.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Let puma talk to systemd
gem "sd_notify"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development do
  gem 'aws-sdk-ec2',        :require => false
  gem 'capistrano',         :require => false
  gem 'capistrano-rails',   :require => false
  gem 'capistrano-rbenv',   :require => false
end

group :test do
  gem 'simplecov',  :require => false
end

group :vscode do
  gem 'debase',           :require => false, :git => 'https://github.com/ruby-debug/debase.git', :tag => 'v0.2.5.beta2'
  gem "ruby-debug-ide",   :require => false
  gem 'solargraph',       :require => false
  gem 'solargraph-rails', :require => false
end
