source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.6"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.3", ">= 7.0.3.1"

gem "unicorn"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development do
  gem 'aws-sdk',            :require => false
  gem 'capistrano',         :require => false
  gem 'capistrano-rails',   :require => false
  gem 'capistrano-rbenv',   :require => false
end

group :test do
  gem 'simplecov',  :require => false
end
